kind: pipeline
name: default
steps:
  - name: docker_test
    image: docker:18.06.3-ce
    commands:
      - apk add --no-cache py-pip curl bash gcc libffi-dev openssl-dev python2-dev musl-dev make && pip install docker-compose
      - docker-compose up -d
      - yes | bash demo.sh http://docker:8080
    volumes:
      - name: dockersock
        path: /var/run
  - name: docker_build
    image: plugins/docker
    settings:
      username: dvdmuckle
      password:
        from_secret: docker_password
      repo: nashenmuck/network
      tag: testing
services:
  - name: docker
    image: docker:18.06.3-ce-dind
    privileged: true
    ports:
    - 8080
    volumes:
      - name: dockersock
        path: /var/run
volumes:
  - name: dockersock
    temp: {}
