kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      username: nashenmuck
      password:
        from_secret: docker_password
      repo: nashenmuck/network
      tag: develop
