kind: pipeline
name: default
steps:
  - name: docker_test
    image: docker
    commands:
      - echo "Random change"
      - docker-compose up -d
      - yes | ./demo.sh
  - name: docker
    image: plugins/docker
    settings:
      username: nashenmuck
      password:
        from_secret: docker_password
      repo: nashenmuck/network
      tag: develop
