sudo: required

language: generic

services:
  - docker
script:
  - docker build -t nashenmuck/network:$TRAVIS_BRANCH -t nashenmuck/network:$TRAVIS_BRANCH-$(echo $TRAVIS_COMMIT | cut -c1-7) .
deploy:
  provider: script
  script: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && docker push nashenmuck/network:master && docker push nashenmuck/network:master-$(echo $TRAVIS_COMMIT | cut -c1-7)
  on:
    branch: master 
deploy:
  provider: script
  script: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && docker push nashenmuck/network:testing && docker push nashenmuck/network:testing-$(echo $TRAVIS_COMMIT | cut -c1-7)
  on:
    branch: testing
