sudo: required

language: generic

services:
  - docker
script:
  - docker build -t nashenmuck/network:$TRAVIS_BRANCH -t nashenmuck/network:$TRAVIS_BRANCH-$(echo $TRAVIS_COMMIT | cut -c1-7) .
deploy:
  provider: script
  script: bash ci/deploy_master.sh
  on:
    branch: master 
deploy:
  provider: script
  script: bash ci/deploy_testing.sh
  on:
    branch: testing
